[package]
name = "ephemeral-sign"
version = "0.1.0"
edition = "2024"

[dependencies]
musig2 = { git = "https://github.com/halseth/musig2.git", branch = "ephemeral-sign" , features = ["rand"]}
secp256k1 = "0.30.0"
digest = "0.10.7"
sha2 = "0.10.8"
hex = "0.4.3"
subtle = "2.6.1"
